# Generated by Django 5.1 on 2024-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
