# Generated by Django 5.1 on 2024-09-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, default='/media/images/default.jpg', max_length=1000, null=True),
        ),
    ]
